### ISSUE TITLE
DIfferent Eglobals

### ISSUE THREAD

**Issue by Kerrnel** [yhl452493373/S210-10880H-DW1560-OpenCore-BigSur#2]
I have https://www.eglobaltech.cn/ViewDetails297.aspx

But it's obviously not S210 (maybe you could post an image) since it has Realtek Ethernet/Wifi.

This EFI hangs with ACPI error soon after start with this model.

**Comment by xvortex** [comment]
This is S500 by eglobaltech specification. also faced this problem. I don’t have a solution yet.

**Comment by yhl452493373** [comment]
> I have https://www.eglobaltech.cn/ViewDetails297.aspx
> 
> But it's obviously not S210 (maybe you could post an image) since it has Realtek Ethernet/Wifi.
> 
> This EFI hangs with ACPI error soon after start with this model.

This EFI is for S210, not the model of S500. The two models do not belong to the same manufacturer.you need to build your own EFI by yourself.you can flow the install guide here: https://dortania.github.io/OpenCore-Install-Guide/prerequisites.html.

these are my pc's image.

![1](https://user-images.githubusercontent.com/26134687/123671006-635e6700-d870-11eb-8c58-0b816be64f56.jpeg)

![2](https://user-images.githubusercontent.com/26134687/123671022-68231b00-d870-11eb-9e63-90e27a373ff4.jpeg)

**Comment by yhl452493373** [comment]
> This is S500 by eglobaltech specification. also faced this problem. I don’t have a solution yet.

I don't have the same device, so I can't fix this problem.you can build your efi fllow the guide here: https://dortania.github.io/OpenCore-Install-Guide/prerequisites.html
