### ISSUE TITLE
可以更新系统吗？

### ISSUE THREAD

**Issue by lxzmads** [yhl452493373/S210-10880H-DW1560-OpenCore-BigSur#3]
感谢你的efi文件，我已经装好了黑果。
最近Big Sur更新了11.5，请问直接在线更新系统会出现什么问题嘛，求解答。

**Comment by yhl452493373** [comment]
直接更新，重启的时候需要手动选下启动磁盘。选第一个Macintosh HD的磁盘即可。更新完成后不用再选
